#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    armPot,         sensorPotentiometer)
#pragma config(Sensor, dgtl2,  Claw1,          sensorDigitalOut)
#pragma config(Sensor, dgtl3,  Lock,           sensorDigitalOut)
#pragma config(Sensor, dgtl4,  REncoder,       sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  LEncoder,       sensorQuadEncoder)
#pragma config(Sensor, dgtl11, Claw2,          sensorDigitalOut)
#pragma config(Sensor, dgtl12, release,        sensorTouch)
#pragma config(Sensor, I2C_1,  baseIME,        sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           RArm1,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           RArm2,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           LFBase,        tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           RFBase,        tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           LBBase,        tmotorVex393TurboSpeed_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port7,           RBBase,        tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           LArm1,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           LArm2,         tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//VRC Specific pragmas below
#pragma platform(VEX)
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)
#include "Vex_Competition_Includes.c"
//VRC Specific pragmas above

#include "5327C_Driver_Control_Functions.h"
#include "5327C_Autonomous_Functions.h"
#include "5327C_Super_Functions.h"
#include "5327C_Autonomous.h"

//--------------------------------------------------------------------------------------------------------//
//-----------------------------------------------PRE_AUTON------------------------------------------------//
//--------------------------------------------------------------------------------------------------------//
void pre_auton(){}

//--------------------------------------------------------------------------------------------------------//
//-----------------------------------------------AUTONOMOUS-----------------------------------------------//
//--------------------------------------------------------------------------------------------------------//
task autonomous
{
	//autonFarRed();
	//autonCloseRed();
	//autonFarBlue();
	//autonCloseBlue();
	//skills();
	auton8000L();
}

//--------------------------------------------------------------------------------------------------------//
//----------------------------------------------USERCONTROL-----------------------------------------------//
//--------------------------------------------------------------------------------------------------------//
task usercontrol()
{
	while(true)
	{
		startTask(autoRelease);
		drive(vexRT[Ch3] , vexRT[Ch2] , vexRT[Btn8U]);
		clawControl(vexRT[Btn5U] || vexRT[Btn5UXmtr2]);
		arm(vexRT[Btn6U] || vexRT[Btn6UXmtr2], vexRT[Btn6D] || vexRT[Btn6DXmtr2], vexRT[Btn8D], vexRT[Ch3Xmtr2], 0.12, 0.5);
		liftLock(vexRT[Btn8U]);
		if(vexRT[Btn7D] == 1)
		{
			startTask(killSwitch);
			auton8000L();

		}
	}
}
//...THE_END...//
